### PR TITLE
Block ETag tracking on outgoing request, instead of incoming response

### LINKED ISSUE #177: upload not working because etag is blocked by this extensions
because the upload use etag to support multipartUpload, but this extensions block etag!

### PR DESCRIPTION
**Pull request by brianhelba**
This change more directly addresses the privacy concern where servers can identify whether a given client has previously downloaded some content. This tracking occurs when a request for an already-cached resource is sent to the server with an `If-None-Match` header. If the cached resource was previously received with a unique `ETag`, the server can uniquely identify the user. Rather than blocking the client from reading `ETag` values (which may be safely be used for other purposes; see #177), this change prevents servers from being informed about whether the client has any cached content.

Fixes #177.

### CODE REVIEW

**Comment by MythicManiac** [comment]
Nice, this would fix the issue we're seeing at least (as described in #177)

**Comment by KevinRoebert** [comment]
LGTM. Thank you

**Comment by KevinRoebert** [comment]
Merged with https://github.com/ClearURLs/Addon/commit/783f1fc99ad2e32d692be0a5626f1184e84fdc20

**Comment by KevinRoebert** [comment]
Unfortunately, this solution does not work because the `If-None-Match` header (this applies to all caching headers) is not included in the `requestHeaders`. This is also described in the Mozilla documentation (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders#section-content).

So filtering the ETags is only possible when receiving, but not when sending.

**Pull request closed without merging**
